# Generated by Django 4.2.6 on 2023-10-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('restock_count', models.IntegerField(blank=True, null=True)),
                ('minimum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
    ]
